const defaultSpecs = {
  Size: ["M", "L"],
  Đá: ["Ít", "Vừa", "Nhiều"],
  Đường: ["0%", "30%", "50%", "70%", "100%"],
};

const products = [
  {
    category: "Cà phê",
    list: [
      {
        id: "caphe-01",
        img: "https://thuytinhocean.com/wp-content/uploads/2024/08/hinh-anh-ly-cafe-den-da-23.jpg",
        name: "Đen đá",
        price: 30000,
        description: "Hương vị cà phê nguyên bản mạnh mẽ chuẩn vị gu mạnh.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "caphe-02",
        img: "https://winci.com.vn/wp-content/uploads/2023/12/Cach-pha-ca-phe-bac-xiu-cho-nguoi-moi-bat-dau.jpg",
        name: "Bạc xỉu truyền thống",
        price: 30000,
        description:
          "Hương vị cà phê nguyên bản kết hợp ăn ý cùng sữa đặc thơm béo.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "caphe-03",
        img: "https://simexcodl.com.vn/wp-content/uploads/2024/02/cach-pha-cafe-hanh-nhan-8.jpg",
        name: "Bạc xỉu hạnh nhân",
        price: 30000,
        description:
          "Hương vị cà phê đậm kết hợp hạnh nhân hòa quyện ăn ý cùng sữa tươi thơm béo.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "caphe-04",
        img: "https://file.hstatic.net/200000079049/article/ban_sao_cach-lam-cafe-bot-bien-4.1_c76abbc31e144a91aabf17656c147fdc.png",
        name: "Cà phê bọt biển",
        price: 35000,
        description:
          "Hương vị cà phê đậm hòa quyện ăn ý cùng sữa tươi thơm béo.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "caphe-05",
        img: "https://athome.starbucks.com/sites/default/files/styles/ingredients_864x864/public/2022-12/22_SBX_COLD%20INNOVATIONS_CAH_COLD%20BREW%20CONCENTRATE_INGREDIENT.jpg.webp?itok=0MNIQrxj",
        name: "Cold brew",
        price: 38000,
        description:
          "Hương vị cà phê với phiên bản nhẹ nhàng ai cũng có thể thử mà không sợ say.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
    ],
  },
  {
    category: "Trà sữa",
    list: [
      {
        id: "trasua-01",
        img: "https://phela.vn/wp-content/uploads/2021/07/14369.jpg",
        name: "O long đậm vị",
        price: 28000,
        description: "Hương vị trà sữa đậm vị đúng gu .",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: true,
      },
      {
        id: "trasua-02",
        img: "https://glofood.vn/upload/baiviet/7dab210981b359ed00a21-2971.jpg",
        name: "O long gạo rang",
        price: 28000,
        description:
          "Hương vị trà sữa đậm hòa kết hợp ăn ý cùng gạo rang bổ dưỡng .",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: true,
      },
      {
        id: "trasua-03",
        img: "https://bizweb.dktcdn.net/100/421/036/files/cach-nau-tra-sua-truyen-thong-de-ban-2.jpg?v=1616644748197",
        name: "Trà sữa Truyền thống",
        price: 25000,
        description: "Hương vị trà sữa đậm đà, pha chế từ lá trà tuyển chọn.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: true,
      },
      {
        id: "trasua-04",
        img: "https://phela.vn/wp-content/uploads/2023/11/PHONG-LAN-scaled.jpg",
        name: "Trà sữa Bá tước",
        price: 28000,
        description: "Hương vị trà sữa đậm đà, pha chế từ lá trà nguyên chất.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: true,
      },
      {
        id: "trasua-05",
        img: "https://phela.vn/wp-content/uploads/2021/07/14287.jpg",
        name: "O long nhài sữa",
        price: 28000,
        description:
          "Hương vị lài thơm hòa cùng o long đậm đà, pha chế từ lá trà nguyên bản.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: true,
      },
      {
        id: "trasua-06",
        img: "https://cherryngoc.vn/wp-content/uploads/2024/07/cach-nau-tra-sua-khoai-mon-3.jpg",
        name: "Trà sữa Ta-go",
        price: 28000,
        description: "Hương vị trà sữa đậm đà kết hợp khoai môn tươi dậy vị.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: true,
      },
    ],
  },
  {
    category: "Matcha",
    list: [
      {
        id: "matcha-01",
        img: "https://recipesblob.oetker.de/assets/a106928ad58e4c56bb072edce6ed87af/750x750/iced-vanilla-matcha.webp",
        name: "Matcha latte",
        price: 35000,
        description: "Hương vị Matcha nguyên chất hòa quyện cùng sữa đậm đà.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "matcha-02",
        img: "https://product.hstatic.net/1000075078/product/1745246651_matcha-dao_8c749d752e0d4d2b85f0a03310bd1379_large.png",
        name: "Matcha bưởi hồng",
        price: 35000,
        description: "Hương vị Matcha kết hợp cùng bưởi chua thanh.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "matcha-03",
        img: "https://cdn.tgdd.vn/Files/2024/03/26/1563635/cach-lam-nuoc-dua-matcha-la-mieng-thu-mot-lan-la-nghien-ngay-202403261039460072.jpg",
        name: "Matcha and coco",
        price: 35000,
        description:
          "Hương vị Matcha truyền thống mix với nước dừa ngọt thanh.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "matcha-04",
        img: "https://xachtaynhat.net/wp-content/uploads/2019/08/Matcha-latte.jpg",
        name: "Matcha sữa dừa",
        price: 35000,
        description: "Hương vị Matcha đậm đà hòa quyện cùng sữa dừa thơm béo.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "matcha-05",
        img: "https://takestwoeggs.com/wp-content/uploads/2021/04/matcha-dalgona-takes-two-eggs-asian-fusion-feature-image.jpg",
        name: "Matcha bọt tuyết",
        price: 35000,
        description:
          "Hương vị Matcha nguyên bản kết hợp cùng sữa tươi thanh trùng tuyệt hảo .",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
    ],
  },
  {
    category: "Trà trái cây",
    list: [
      {
        id: "tratraicay-01",
        img: "https://coffee.vntheme.com/wp-content/uploads/2022/09/TRA-DAO-CAM-SA.png",
        name: "Đào cam xả",
        price: 25000,
        description:
          "Hương vị đào ngọt nhẹ, kết hợp cam tươi mọng nước và xả thơm mát – tươi mới và dễ chịu.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: true,
      },
      {
        id: "tratraicay-02",
        img: "https://goldenfarm.com.vn/wp-content/uploads/dao-nhai-hibicus-1.webp",
        name: "Hibiscus mix bưởi",
        price: 25000,
        description:
          "Vị chua thanh của Hibiscus hoà quyện cùng bưởi mọng nước, mang đến cảm giác tươi mát, nhẹ nhàng và cực kỳ giải khát.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: true,
      },
      {
        id: "tratraicay-03",
        img: "https://sieuthinguyenlieu.com/assets/uploads/images/Tj4rJIR4XuMZ_o-long-sen-vang-la-dua-web.jpg",
        name: "Trà thư giãn",
        price: 25000,
        description:
          "Trà ô-long ủ cùng hương sen vàng dịu nhẹ, điểm thêm chút lá dứa thơm thoang thoảng – một sự kết hợp thư giãn và thanh lọc cơ thể.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: true,
      },
      {
        id: "tratraicay-04",
        img: "https://glofood.vn/upload/images/TRA%20VAI%20HOA%20HONG(2).png",
        name: "Yu-zu vải",
        price: 30000,
        description:
          "Vị thanh mát, hơi the nhẹ của Yu-zu Nhật Bản kết hợp với độ ngọt dịu từ trái vải sảng khoái và độc đáo, khó quên ngay từ ngụm đầu tiên.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: true,
      },
      {
        id: "tratraicay-05",
        img: "https://www.huongnghiepaau.com/wp-content/uploads/2022/08/hong-tra-tac-co-vi-chua-ngot.jpg",
        name: "Hồng trà tuổi thơ",
        price: 15000,
        description:
          "Vị trà đậm đà gợi nhớ về ly trà tắc sủi bọt ngày xưa thân quen và đầy hoài niệm. ",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: true,
      },
    ],
  },
  {
    category: "Topping",
    list: [
      {
        id: "topping-01",
        img: "https://product.hstatic.net/200000516795/product/upload_2f751925f1e543cb9158e5a64b7ed09a_master.jpg",
        name: "Trân châu đường đen",
        price: 3000,
        description: "Trân châu nấu với đường đen thơm ngọt, mềm dai.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "topping-02",
        img: "https://viettuantea.vn/wp-content/uploads/2020/09/tran-chau-tuyet-trang.jpg",
        name: "Trân châu 3Q",
        price: 3000,
        description:
          "Dai giòn sần sật, kết hợp hoàn hảo với mọi loại thức uống.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "topping-03",
        img: "https://namangroup.vn/wp-content/uploads/2025/01/lam-pudding-trung-bang-bot-pudding-3.jpg",
        name: "Pudding trứng",
        price: 3000,
        description: "Mềm mịn, béo nhẹ, tan chảy trong miệng.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "topping-04",
        img: "https://cdn.tgdd.vn/2021/03/CookRecipe/GalleryStep/thanh-pham-1171.jpg",
        name: "Pudding cho-co",
        price: 3000,
        description: "Vị ca cao thơm đậm, ngọt vừa, mềm mát dễ ghiền.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "topping-05",
        img: "https://raumaluck.vn/wp-content/uploads/2024/09/Thach-Suong-Sao.png",
        name: "Thạch sương sáo",
        price: 3000,
        description: "Mát lạnh, vị nhẹ thanh – giúp cân bằng vị ngọt.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "topping-06",
        img: "https://cdn2.fptshop.com.vn/unsafe/cach_lam_pho_mai_vien_1_10de8b9e05.JPG",
        name: "Phô mai viên",
        price: 5000,
        description: "Phô mai mềm mịn, vị béo nhẹ nhàng.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
      {
        id: "topping-07",
        img: "https://phela.vn/wp-content/uploads/2025/06/Resize-AppFood-KV-OLongDaoHong-2-09-scaled.jpg",
        name: "Thạch trà đào hồng",
        price: 3000,
        description:
          "Vị đào dịu nhẹ, thơm mát, tăng thêm sắc hương cho ly nước.",
        specs: defaultSpecs,
        isFeatured: true,
        customizable: false,
      },
    ],
  },
];

export { products };
